### ISSUE TITLE
Potentially restrict the Preferences -> Notifications "Allow other users to PM me" option?

### ISSUE THREAD

**Issue by quackbox** [roblox-dev-forum/tl-restrict-preferences#2]
Hey guys, under Preferences -> Notifications there's an option to completely disable/enable other users PMing you on the forum.

![image](https://user-images.githubusercontent.com/49273992/66381559-baffd380-e9f8-11e9-9a26-4cbae3ef3558.png)

I don't believe there's a vanilla setting to disable the preference (at least, I couldn't find one on my dev build). Would it be outside the scope of this plugin to restrict the setting from certain trust levels? While discourse mods/admins can msg the user still (and possibly TL4, not sure) it prevents collaborative discussion and feedback between normal members.

Thanks.

**Comment by buildthomas** [comment]
https://github.com/roblox-dev-forum/disable-hide-presence
